add user agent and try catch

diff --git a/run b/run
--- a/run
+++ b/run
@@ -9,7 +9,7 @@ if [[ ! -d "$day" ]]; then
 	mkdir "$day"
 	cp ./template.js "$day/solve.js"
 	sed -i "s/__DAY__/$day/g" "$day/solve.js"
-	curl -b session=$ADVENT_OF_CODE_SESSION "https://adventofcode.com/${year}/day/${day}/input" > "$day/input.txt" || echo "Failed to download input from Advent of Code!"
+	curl -A "github.com/guillaumebrunerie/advent-of-code-2024" -b session=$ADVENT_OF_CODE_SESSION "https://adventofcode.com/${year}/day/${day}/input" > "$day/input.txt" || echo "Failed to download input from Advent of Code!"
 	./extractTestInputs "https://adventofcode.com/${year}/day/${day}" "$day"
 fi
 
