download input and test inputs automatically

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,13 +1,16 @@
 #!/bin/zsh
 
+source .env
+
+year=2024
 day=${1:-$(date '+%-d')}
 
 if [[ ! -d "$day" ]]; then
 	mkdir "$day"
 	cp ./template.js "$day/solve.js"
 	sed -i "s/__DAY__/$day/g" "$day/solve.js"
-	touch "$day/testInput.txt"
-	touch "$day/input.txt"
+	curl -b session=$ADVENT_OF_CODE_SESSION "https://adventofcode.com/${year}/day/${day}/input" > "$day/input.txt" || echo "Failed to download input from Advent of Code!"
+	./extractTestInputs "https://adventofcode.com/${year}/day/${day}" "$day"
 fi
 
 node --stack-size=100000 "$day/solve.js"
